### ISSUE TITLE
Not detecting bl2 INI files on linux

### ISSUE THREAD

**Issue by ZetaDaemon** [BLCM/OpenBLCMM#26]
OpenBLCMM Version: 1.3.3
Java Version: 20.0.1
Java VM: OpenJDK 64-Bit Server VM 20.0.1+9
Memory Used: 77.1 MB
Memory Max: 2.1 GB
BL2 Data: Loaded, v2023.04.03.01
TPS Data: Loaded, v2023.04.03.01
AODK Data: Not loaded: No jarfiles found for AODK

Bl2 INI files are not being detected on linux despite the fact that TPS INI files are being detected, both are installed in the same way on the same drive, specifically having the windows versions of the games installed.
Possibly allow for manually specifying INI file location in case of failure to detect?

**Comment by apocalyptech** [comment]
Thanks for the report, btw -- At least tangentially related to #10...  Would you mind attaching a logfile with what's happening on your machine?  On mine it's detecting the INI files for both, so I'll clearly have to track something down here.  Thanks!

**Comment by ZetaDaemon** [comment]
[log-latest.log](https://github.com/BLCM/OpenBLCMM/files/11781003/log-latest.log)
very strange, seems to have found the ini files but its still telling me it found them? Oddly this bug has followed me from ubuntu to fedora and blcmm to openblcmm

**Comment by apocalyptech** [comment]
Okay, fun fun -- we got to the bottom of this in Discord.  Turns out it was a case-sensitivity issue.  The actual path component on-disk was `My games` (lowercase `g`), whereas the detection was using `My Games` (uppercase `G`).  Wine/Proton itself doesn't care, since there's a case-insensitivity layer baked in there, but native access would need to use the correct case.

So, I put in a hideous little check for Linux where if we don't find the INI file on the given path, it'll walk the tree and look for case-insensitive alternatives.  There's probably some other places where we could be doing the same, but I can't quite bring myself to do the necessary debugging to integrate it anywhere else, and I think the INI files are probably the most likely source of this issue anyway.
