### ISSUE TITLE
Mousing over interactables as well as names to show explaination dialogue.

### ISSUE THREAD

**Issue by Lilu-VA** [BLCM/OpenBLCMM#27]

**Comment by apocalyptech** [comment]
Aha, thanks for the bugreport -- sorry I didn't notice until now!  Turns out I hadn't been set up to get emails when new Issues are put in.

For my own reference later: this is specifically in re: the INI tweaks dialog.  Right now the mouseover explanation text only shows up on the description on each line, not on the buttons themselves.  Would be a better experience for users to have them on the buttons too.

**Comment by apocalyptech** [comment]
Okay, this was pushed up to the `new` branch, and will be a part of v1.4.0, whenever that releases.  Cheers, and thanks again for the report!
