### ISSUE TITLE
Native Linux Executable 

### ISSUE THREAD

**Issue by apple1417** [BLCM/OpenBLCMM#29]
A lot of steam deck users are having trouble because java does not come preinstalled, and the deck has a mostly read only filesystem by default making it hard to install it. A native executable, similarly to the windows one, would help alleviate this.

**Comment by apocalyptech** [comment]
So it turns out that the static linking on GraalVM-compiled stuff is quite minimal, which is nice:

```
$ ldd ./OpenBLCMM
        linux-vdso.so.1 (0x00007ffe9e3f6000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f99e577a000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f99e5590000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f99eaa1a000)
```

So theoretically once it's straightened out, it should be pretty portable.  At the moment, my test compile on a SteamOS VM seems to work great there, but fails on my main Arch desktop with the error `UnsatisfiedLinkError: no awt in java.library.path`.  It could be that I need to run through the native-image agent stuff on a few desktops to make sure that all the JNI/Reflection stuff is good, and make sure to build using the conglomerate of all those.

Anyway, for now I'll try to find some testers to see if it works on *real* Steam Decks.  I suppose in the absence of testers I could still release it once v1.4.0 drops, and make sure that it's very obviously marked as experimental.

**Comment by apocalyptech** [comment]
Oh, a note for myself so I don't forget -- and this isn't really native-image related, but: it looks like SteamOS is one of those environments which doesn't have a configured OS-level "open this http link" action, so clicking URL buttons in there leads to our newish could-not-launch-URL dialog.  I'd like to take a peek to see if there's some alternative which makes sense in there, or if that dialog's really the most sensible option.

**Comment by apocalyptech** [comment]
Okay, various notes, primarily for my own sake.  I have yet to actually find a Steam Deck user to try it out, though I've got pretty decent faith that it'll work.

# Compiling

Pretty straightforward; need to do some extra shenanigans to get the necessary stuff installed in SteamOS, but this does the trick:

```
steamos-readonly disable
pacman-key --init
pacman -S archlinux-keyring
pacman -S base-devel glibc linux-api-headers
steamos-readonly enable
```

Then grab Liberica NIK, unpack it, and `native-image -jar OpenBLCMM.jar` (or `native-image -march=foo -jar OpenBLCMM.jar`, if you like -- see below).

# Architecture

The `native-image` compilation process lets you choose an architecture target, so that it can do as much optimization as it can.  The *most* performant version would be to compile on a Deck itself, using `-march=native`, but honestly I expect the performance gains between a lot of these are minimal at best, at least for an interactive app like OpenBLCMM.  It might make sense to build with a more general profile anyway, so that the image can be used on more than just Steam Decks (though Linux users should probably just use the Java version anyway).

The default target, when compiling on an AMD system anyway, is `x86-64-v3`, which I assume is a decent balance between potential performance gains and widespread hardware availability.  I'm planning on just keeping that at the default.  Given the Deck's CPU flags, it looks like we could get more aggressive, with either `haswell` or `skylake`, even though those seem to be Intel designations.  But still, we'll just stick with `x86-64-v3`.

(Note that if compiling on a SteamOS *VM*, the default may not be `x86-64-v3` -- my own SteamOS VM doesn't provide all the necessary CPU flags for that, so it ends up downgrading to `compatibility`.  You should still be able to force a "better" profile like `x86-64-v3`, though the results may not actually run on the VM.)

## Steam Deck CPU flags:

(Provided by a helpful user in Libera's #steamlug.)

```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36
clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm
constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni
pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx
f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse
3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext
perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp
vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt
clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc
cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc
arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid
decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl
umip rdpid overflow_recov succor smca sme sev sev_es
```

## native-image `-march=foo` targets:

(It'll also list a `native` version which will show you the optimizations it can do on the host doing the compilation.)

```
   'x86-64'
      CPU features: cx8 + cmov + fxsr + mmx + sse + sse2
   'x86-64-v1'
      CPU features: all of 'x86-64'
   'x86-64-v2'
      CPU features: all of 'x86-64-v1' + sse3 + ssse3 + sse4_1 + sse4_2 + popcnt
   'x86-64-v3'
      CPU features: all of 'x86-64-v2' + lzcnt + avx + avx2 + bmi1 + bmi2 + fma
   'x86-64-v4'
      CPU features: all of 'x86-64-v3' + avx512f + avx512dq + avx512cd + avx512bw + avx512vl
   'compatibility'
      CPU features: all of 'x86-64'
   'haswell'
      CPU features: all of 'x86-64' + sse3 + ssse3 + sse4_1 + sse4_2 + popcnt + lzcnt + avx + avx2 + aes + clmul + bmi1 + bmi2 + fma
   'skylake'
      CPU features: all of 'haswell' + amd_3dnow_prefetch + adx + flushopt
   'skylake-avx512'
      CPU features: all of 'skylake' + avx512f + avx512dq + avx512cd + avx512bw + avx512vl + clwb
```

Some flags listed there aren't listed by the exact names that they show up in `/proc/cpuinfo`; I'm pretty sure that these mappings are correct, and account for all relevant differences (some of these, like lzcnt->abm, may be AMD-specific):

* `sse3` -> `pni`
* `lzcnt` -> `abm`
* `clmul` -> `pclmulqdq`
* `amd_3dnow_prefetch` -> `3dnowprefetch`
* `flushopt` -> `clflushopt`

# Linking

I hadn't noticed during my initial tests that the compilation process generates a bunch of `.so` dependencies, much like the Windows compilation generates a bunch of DLLs.  These are needed to run the app, even though the app doesn't *directly* link to any of 'em when queried via `ldd`, for instance.  While the linking on the main app binary is quite minimal, some of the `.so` libraries link out to various system components, like X stuff.  So it's not as static as it could be.

However, at the moment at least, compiling on my main Arch desktop will produce a binary which will run on my SteamOS VM, at least, so for the time being it looks like you may not *have* to compile inside SteamOS to get a Steam Deck compatible build.  If SteamOS ends up diverging from mainline Arch, though, that could change in the future, and it's always possible that updates to Arch mainline might not land in SteamOS for awhile, so compiling on current SteamOS is *probably* the safest bet regardless.

Here's the linking for everything, when investigated on my Arch desktop:

```
libawt_headless.so:
        linux-vdso.so.1 (0x00007ffded95f000)
        libawt.so => ./libawt.so (0x00007fda9d800000)
        libjvm.so => ./libjvm.so (0x00007fda9df3a000)
        libjava.so => ./libjava.so (0x00007fda9df35000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fda9db13000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fda9ded7000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fda9d616000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007fda9df41000)
libawt.so:
        linux-vdso.so.1 (0x00007ffc7a185000)
        libjvm.so => ./libjvm.so (0x00007f3b54486000)
        libjava.so => ./libjava.so (0x00007f3b54481000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f3b5433b000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f3b54336000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f3b53e16000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f3b5448d000)
libawt_xawt.so:
        linux-vdso.so.1 (0x00007ffde6fe1000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f6745f13000)
        libawt.so => ./libawt.so (0x00007f6745c00000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f674626c000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f6745abd000)
        libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f674625f000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f6745f0e000)
        libXtst.so.6 => /usr/lib/libXtst.so.6 (0x00007f6745f04000)
        libXi.so.6 => /usr/lib/libXi.so.6 (0x00007f6745ef0000)
        libjava.so => ./libjava.so (0x00007f6745ab8000)
        libjvm.so => ./libjvm.so (0x00007f6745ab3000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f6745aae000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f67458c4000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f67462dc000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f6745899000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f6745894000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f674588c000)
libfontmanager.so:
        linux-vdso.so.1 (0x00007ffed0766000)
        libfreetype.so => ./libfreetype.so (0x00007f71fe600000)
        libawt.so => ./libawt.so (0x00007f71fe200000)
        libjava.so => ./libjava.so (0x00007f71fefc9000)
        libjvm.so => ./libjvm.so (0x00007f71fefc4000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f71fee7e000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f71fe016000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f71fefd0000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f71fee77000)
libfreetype.so:
        linux-vdso.so.1 (0x00007ffda8727000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f36f9e16000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f36fa49a000)
libjavajpeg.so:
        linux-vdso.so.1 (0x00007ffc50fdb000)
        libjava.so => ./libjava.so (0x00007f2d6ad04000)
        libjvm.so => ./libjvm.so (0x00007f2d6acff000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f2d6a816000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f2d6ad0b000)
libjava.so:
        linux-vdso.so.1 (0x00007fffd6f5f000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f2c6dc6f000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f2c6deb9000)
libjsound.so:
        linux-vdso.so.1 (0x00007ffe739af000)
        libjava.so => ./libjava.so (0x00007f8808830000)
        libjvm.so => ./libjvm.so (0x00007f880882b000)
        libasound.so.2 => /usr/lib/libasound.so.2 (0x00007f88084b7000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f88082cd000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f88081e0000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f8808837000)
libjvm.so:
        linux-vdso.so.1 (0x00007ffe460c6000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fe50acce000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe50af18000)
liblcms.so:
        linux-vdso.so.1 (0x00007ffef3772000)
        libawt.so => ./libawt.so (0x00007fe18ae00000)
        libjvm.so => ./libjvm.so (0x00007fe18b603000)
        libjava.so => ./libjava.so (0x00007fe18b5fe000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fe18b4b8000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fe18ac16000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fe18b4b1000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe18b60a000)
OpenBLCMM:
        linux-vdso.so.1 (0x00007ffd97be5000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f754fdbd000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f754fbd3000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f75551ba000)
```

# Bugs

There's a couple of known issues at the moment:

1. Fonts look pretty bad.  I [opened a bug at Liberica's tracker](https://github.com/bell-sw/Liberica/issues/140); we'll see if that goes anywhere.
2. SteamOS, as it turns out, is one of those environments where Java's "open browser" action doesn't work, so users will get that custom dialog instead, where the URL is copyable.
    1. It turns out that Java's implementation of that depends on having "gvfs" installed.  On some distros, that means installing something like `gvfs-libs`, but on Arch/SteamOS the package is just `gvfs`.  So to have that functionality, you've gotta `steamos-readonly disable && pacman -S gvfs && steamos-readonly enable`, and cope with the fact that that install will disappear when any SteamOS updates happen.  (You'd also have to have gotten pacman activated first).
    2. We *could* have the URL-launch functions try to fall back to `xdg-open` on Linux, which should work regardless of `gvfs`'s presence, though it looks like SteamOS might not have a browser installed by default?  So if we did that, doing an action which would open a URL could just pop up SteamOS's flatpak manager instead...
    3. Alternatively, if we wrapped everything up in a Flatpak, can gvfs be installed in there "enough" to make it work?
3. Not technically a bug yet, but I have yet to make sure that BLCMM can "see" installed BL2/TPS/AoDK games on there, for INI Tweaks + Legacy Hexedits.

# Flatpak?

Flatpak is Steam Deck's recommended method of installing "extra" software, 'cause it resides in `/home` and survives updates.  Maybe it'd be good to wrap OpenBLCMM up in that, as well?  If it went so far as to get on flathub (or whatever that's called), installation could be just a few clicks away.  I'm hesitant to do so with the current font issue, though, so we'd have to see.  I'd also have to figure out how that would interact with datapacks; might need to figure out a solution for those.

**Comment by apocalyptech** [comment]
Well, I'd forgotten to mention this issue in the commit comment, but commit 2e65334 added in docs + support scripts for building a native SteamOS release, so I think I'll go ahead and consider this closed.  Will probably continue to be labelled "experimental" for the time being; we'll see if we ever get feedback for it.

**Comment by apocalyptech** [comment]
One final note re: architecture, just to have the notes available in here.  The `-march` arg started to be available in GraalVM 23 (actually called "GraalVM for JDK 17" or whatever, I guess), and I was curious about what the effective default was in GraalVM 22 and earlier.  (The v1.3.0 versions of OpenBLCMM for Windows were compiled with GraalVM 22.)  Anyway, I asked in their community support Slack and got this back:

> The effective default was SSE+SSE2 on AMD64 and FP+ASIMD on AArch64 (see [here](https://github.com/oracle/graal/pull/6112/files#diff-17b1bdb444bc38e95516045e68369cddccca31a322a78dffce03d545c0d23992L442-L491)). Compatibility is CMOV+CX8+FXSR+MMX+SSE+SSE2 on AMD64 and FP+ASIMD on AArch64, so very close to the old default.

So, good to know.  For the SteamOS builds I'm provisionally using the new default of `x86-64-v3`, and keeping the Windows builds on `compatibility`.
