### ISSUE TITLE
Allow copying of folders and commands from one instance of OpenBLCMM to another

### ISSUE THREAD

**Issue by ZetaDaemon** [BLCM/OpenBLCMM#38]
You can copy and paste folders, commands and comments around inside a single blcmm instance, would be nice to be able to do it cross instances as well

**Comment by apocalyptech** [comment]
Yeah, I agree this would be good, though I think I'm inclined to leave this as a subset of #8 rather than trying to tackle it on its own.  (Which would technically be sidestepping the issue -- rather than supporting multi-instance copying, it'd be copying between multiple instances running under the same JVM.)  I've updated the description over there to include this, and I think I'll close this one out and mark it as a duplicate.

If you'd prefer I track this separately, I can re-open, though.  :)
