### ISSUE TITLE
Please allow an option that would allow set command to not be forced to go down the next command line, this is an issue for 2 very useful Behaviors. 

### ISSUE THREAD

**Issue by Zazk0u** [BLCM/OpenBLCMM#39]
Being able to use a set command in conjunction of a Behavior_ConsoleCommands/Behavior_ClientConsoleCommand without having to open the BLCM file raw and manually edit it would be very appreciated.

https://github.com/BLCM/OpenBLCMM/assets/72308078/c7bb3323-dc12-4df1-aeca-52a857b5c578

**Comment by apocalyptech** [comment]
Hello!  Thanks for the report!  Turns out that's something that's already been fixed in the `next` branch, and will be part of v1.4.0, whenever that comes out (see #4).  For now, if you want that fix, you'll have to build up the `next` branch yourself (keeping in mind that `next` isn't always 100% stable) -- otherwise, I'm hoping to get 1.4.0 out within the next month or so.

Cheers!
