### ISSUE TITLE
Opening large statements in mod files takes 17+ seconds while the app fully freezes.

### ISSUE THREAD

**Issue by AceKuper** [BLCM/OpenBLCMM#45]
**System Info**
**Operating System:**
Windows 10

**Describe the bug**
Opening large statements in mod files takes 17+ seconds while the app fully freezes.

**To Reproduce**
As an example trying to open GD_Iris_GameStages.Balance.Iris_P2_GameBalance in the
NVHM/TVHM Area Scaling v1.2 by 55tumbl Mod.

**Comment by apocalyptech** [comment]
Heya -- thanks for the report!

So we'd talked about this on Discord already, but for the record here: I think that this actually sort of accidentally got fixed in some of my original v1.4.0 work fixing issue #4.  It looks like the current `next` branch already handles this pretty well.

I do want to run some more comparisons with other versions (and the original BLCMM code) just to doubly-confirm what the differences are, but I think this one's probably accidentally already fixed for the next forthcoming release.

**Comment by apocalyptech** [comment]
Aha, okay, interesting!  So this was a problem that was introduced w/ OpenBLCMM's initial v1.3.0 release -- the actual code-formatting code didn't really change from BLCMM 1.2.0 -> OpenBLCMM 1.3.0, but one thing that *did* change was the implementation of a BLCMM helper func `StringUtilities.substringStartsWith()`.  That was part of one of the not-opensourced bits of BLCMM, so it had to be reimplemented for OpenBLCMM, and it turns out that my own implementation is quite a bit slower.  I'd basically just made it a naive wrapper around `s.substring(startIndex, endIndex).equals(searchString)`, and apparently that is pretty inefficient for the JVM.  (The `substring` call in particular presumably has to allocate a new String object, etc.)  The original BLCMM implementation looks like it was probably more streamlined.

Anyway, there was one code-formatting routine (`putSetCommandsOnNewlines`) which used to make a few calls into that in the original code, and so that was the source of the slowdown.  In the process of working through issue #4, the code-formatting code was given a bit of an overhaul, and the `putSetCommandsOnNewlines` routine was removed entirely, which sidesteps the inefficiences in `StringUtilities.substringStartsWith`, so the `next` branch is quite a bit snappier for this.

That substring routine is still called in a few other places, though, so I think I'll keep this open and streamline that thing a bit more, anyway.

**Comment by apocalyptech** [comment]
Okay, so I've got a faster implementation of `StringUtilities.substringStartsWith` in place now, so I'll close this out.  (As mentioned above, that's tangential at best to the actual performance issue brought up here, though the fix would've helped out for code still in v1.3.x.)
