### ISSUE TITLE
Unwrapping all\specific levels of nested things into the selected top folder

### ISSUE THREAD

**Issue by AceKuper** [BLCM/OpenBLCMM#49]
Right clicking the folder and an option of "Unwrap into current category" appears so no matter how many folders are inside all of their code get moved to the selected top category. 

For example we have folders named 1-4, each number inside previous one. So if i right click on Folder 3 selecting "Unwrap into current category" code from folder 4 gets moved to 3. Click on 2 code from 3 and 4 gets into 2. Just leaving empty folders behind.

 Would help a lot with adjustments to some older mods that have a ton of nesting.

**Comment by apocalyptech** [comment]
Yeah, seems like a good idea.  I may also add some kind of "Remove Folder" option to do the less-invasive "replace this folder with its contents" sort of action as well.  (Basically an inverse "Introduce Category.")

As I mentioned on Discord, I think I'd actually prefer to just remove folders rather than leave 'em, for the flattening action.  It's already a "destructive" action; folks can always reload the file instead of saving (or restore from the backup dir) if they have second thoughts.  :)  Might make sense to have a confirmation dialog for that one, I suppose...

**Comment by apocalyptech** [comment]
Okay, so these should be in place now.  Ended up using "flatten" to describe them rather than "unwrap."  As I suggested above, there's actually two new actions:

1. "Totally flatten category" -- this is the one you proposed
2. "Flatten/Remove single category" -- this was my own midway point, just the inverse of "Introduce category"

These are committed on the `next` branch, and should be a part of the forthcoming v1.4.0.
