### ISSUE TITLE
Flatten Category and Dragging Files from folders

### ISSUE THREAD

**Issue by AceKuper** [BLCM/OpenBLCMM#61]
Flatten Category doesn't preserve the order of files inside folders if there are multiple folders inside each other. It doesn't put files in order of Top Folder + any folder inside of it, to Bottom Folder. Especially if folders in the middle have folders, order gets all sorts of messed up.

Same with selecting and dragging files from different multi level nested folders. They seem to only go up one folder at a time.

Causes issues with some older mods there are many nested folders and order from top to bottom is important somehow.

**CORRECTION**

What's actually seems to happen with flatten I think it actually inverts the order. Maybe stuff in the middle gets shuffled too, but i'm not sure about that.

While Selecting all the code from all those nested folders and trying to drag it to the source blue folder Elements stay selected, but you aren't actually moving ones in different folders.

I never noticed but it turns out you can't actually select things from different folders and cut\copy or edit them, you can only delete them.

**Comment by apocalyptech** [comment]
Okay, tracked this down, and yeah -- this was always kind of busted.  Basically it was processing stuff in the right order, but it would query the tree for the "current" position of the category and then start injecting there, but it was also removing categories as it walked the tree, so the current position would end up right on top of the new stuff that was inserted, due to some weirdness with the original structure.  The reverse-ordering wasn't even the only way this would manifest; if there were comments or commands inbetween categories, the flattened category could end up a weird semi-merged mishmash.

Anyway, keeping track of the initial positions and new offsets manually and acting appropriately fixes it up.  I think I've got it working but will need to run it through a few more tests in a bit before committing.

**Comment by apocalyptech** [comment]
Okay, committed to `main`; will be a part of v1.4.1 when that releases (probably by Monday)
